const params = new URLSearchParams(window.location.search);
let plantId = params.get('id');

let image = document.getElementById("plant_img");
let name = document.getElementById("name");
let information = document.getElementById("info");

function goBack() {
    if (plantId <= 12) {
        window.location.href = "../Blood/Blood.html";
    } else if (plantId > 12 && plantId <= 24) {
        window.location.href = "../Veshkat/Veshkat.html";
    } else if (plantId > 24 && plantId <= 36) {
        window.location.href = "../Stomach/Stomach.html";
    } else if (plantId > 36 && plantId <= 48) {
        window.location.href = "../Lungs/Lungs.html";
    } else if (plantId > 48 && plantId <= 60) {
        window.location.href = "../Brain/Brain.html";
    }
}

document.addEventListener('DOMContentLoaded', function() {
    if (plantId === "1") {
        image.src = "../../Images/Grami.jpg";
        name.textContent = "Grami";
        information.textContent = "VETITË:\n" + "Në saje të glucideve, esencës etj., droga nxit urinimin, duke ndihmuar veprimtarinë e veshkave dhe përdoret si mjet që pastron organizmin. Këshillohet përdorimi në pezmatimin e pjesëve të poshtme të rrugëve urinare, në reumatizëm dhe sëmundje të lëkurës. Krahas këtyre veprimeve, rizoma e gramit ndihmon në mjekimin e hipertensionit arterial dhe mund të përdoret me dobi si vetëm, ashtu dhe e kombinuar me gjethe ulliri, me gjethe rozmarine, me degë vjeshtulli etj. Në saje të triticines së ngjashme me inulinën, droga përdoret si ndihmëse në sëmundjen e diabetit.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë supe me drogë të thërrmuar (5 g) futet në një enë ku shtohet një gotë me ujë (150–200 g) dhe zihet 10 minuta, pastaj çaji kullohet dhe pihet i ëmbëlsuar me sheqer ose mjaltë, sipas dëshirës. Gjatë ditës merren 2 ose 3 doza të tilla." ;
    } else if (plantId === "2") {
        image.src = "../../Images/i_zemrs.jpg";
        name.textContent = "Leonuri i zemrës";
        information.textContent = "VETITË:\n" + "Bari i leonurit të zemrës përmban një lëndë të hidhur të quajtur leonurinë, rrëshirë, esencë, alkaloidin leonukardinë etj. Në saje të kësaj përmbajtjeje, bari i leonurit është 3 deri 4 herë më i efektshëm se rrënja e valerianës dhe ka veti kardiotonike, hipotonike dhe qetësuese. Duhet të përdoret gjithnjë sipas këshillës dhe nën mbikëqyrjen e mjekut. Këshillohet në rrahje të forta të zemrës, si dhe në shtrëngimin e saj, në ngacmimet nervore, në rastet e lëkundjes ose të rritjes së presionit të gjakut, në çrregullimet e menopauzës dhe në rastet e çrregullimit të urinimit. Veprimi diuretik mendohet se vjen nga veprimi i leonurit në muskulaturën e zemrës. Këshillohet në dhembjet e gjoksit që shoqërohen me të marrurit frymë dhe me ndjenjën e frikës nga vdekja (angina pektoris).\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Dy lugë çaji me bar të grirë imët hidhen në një enë ku shtohet një filxhan çaji me ujë që zien. Ena mbyllet me kapak dhe përmbajtja lihet për gjysmë ore në qetësi. Pastaj, lëngu kullohet dhe pihet. Merren një dozë e tillë në ditë. Droga mund të përdoret edhe në formë pluhuri; merren 1 deri 2 lugë kafeje në ditë.";
    } else if (plantId === "3") {
        image.src = "../../Images/livando.jpg";
        name.textContent = "Livando";
        information.textContent = "VETITË:\n" + "Në saje të esencës (të pasur me acetat linalili), tanineve, fitoncideve etj., lulet e livandos kanë veti të qetësojnë sistemin nervor qendror, të ulin deridiku presionin e ngritur të gjakut, të qetësojnë ngërçet e stomakut dhe të zorrëve, të rregullojnë veprimtarinë e zorrëve në rastet e heqjes së barkut dhe të fryrjes së tyre nga gazat; shtojnë jashtëqitjen e urinës. Duke u bazuar në vetitë e mësipërme, droga këshillohet si mjet që qetëson nervat, p.sh. në neurasteni, në rrahjet e forta të zemrës, në migrenë, në pështjellim dhe në pagjumësi. Lehtëson dhembjet që vijnë nga ngërçi. Këshillohet, gjithashtu, në çrregullimet e stomakut dhe të zorrëve, që vijnë nga heqja e barkut etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "3 lugë çaji me lule hidhen në një enë, ku përvëlohen me 1 gotë me ujë që zien; ena mbulohet me kapak dhe lihet 15–30 minuta në qetësi; lëngu kullohet dhe pihet 1 herë në dy ditë.";
    } else if (plantId === "4") {
        image.src = "../../Images/Bar_gjaku.jpg";
        name.textContent = "Bar gjaku";
        information.textContent = "VETITË:\n" + "Droga ka veti të ndryshme, në sajë të substancave që përmban. Kështu, p.sh., në sajë të tanineve dhe të esencës, droga jep rezultate të mira në diarre që shoqërohen me një humbje të tonusit (të shtrëngimit) të zorrëve, kurse në sajë të mucilagjeve ka edhe veti qetësuese. Është provuar se, në sajë të salikarines (heterozid), droga ka edhe veti që të ndalojë rrjedhjen e gjakut (hemorragjinë), të rrudhë brenda një kohe të shkurtër mukozën e zorrëve, si dhe veti specifike më dizinfektuese rinë bacilare. Droga ka edhe veti të lehta antibiotike. Në rastet të përshkruara më lart, rekomandohet edhe në gastroenterit, në tifo dhe në dizanteri.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "30 ose 40 g drogë e grimcuar hidhen në një enë të zingjar ku përvëlohen me 1 litër ujë që zien; ena mbulohet me kapak dhe lihet për 15 minuta sa të ftohet, pastaj çaji kullohet nëpërmjet një nape. Pihen 300 deri 500 g çaj në ditë.";
    } else if (plantId === "5") {
        image.src = "../../Images/Metriku.jpg";
        name.textContent = "Metriku";
        information.textContent = "VETITË:\n" + "Droga përmban alkaloide, karoten, vitaminë C, saponine, tanine, pektinë, derivate flavonike, etj. Ndërmjet alkaloideve që janë izoluar deri më sot nga kjo drogë, më kryesoret janë vinkamajoridina, vinkamajina, rezepina, etj. Ka autorë që kanë provuar se metrikë ka veti të ngjashme me ato të bimës Vinca minor L., e cila nuk është takuar në vendin tonë. Në sajë të tanineve, ekstraktet e drogës kanë veti hemostatike e rrudhëse; ato përdoren edhe për të pakësuar ngacmimin e kollës. Alkaloidet ulin presionin e lartë të gjakut. Në formë çaji, droga ndikon në ndalimin e hemorragjive me origjinë të ndryshme, si p.sh. në rrjedhjet e gjakut nga hunda, mishrat e dhëmbëve, organet gjenitale. Përdoret në pezmatimet e mukozës së zgavrës së gojës dhe në pezmatimet e bronkeve dhe të mushkërive. Po në formë çaji, bari i mëtrikut përdoret nga populli kundër pezmatimit të aparatit të tretjes dhe të aparatit genitourinar; përdoret nga gratë për pakësimin e qumështit të gjirit. Nga jashtë droga përdoret në formë valese (dekokt) për mjekimin e acarimeve të gojës e të fytit (si gargërizëm), si dhe për shërimin e ekzemës e të sëmundjeve të tjera të lëkurës.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë çaji me drogë të grimcuar hidhet në një enë ku shtohet një filxhan me ujë që zien dhe përmbajtja lihet 15 minuta; pastaj ajo kullohet dhe lëngu ëmbëlsohet sipas dëshirës e pihet; merren 2 doza të tilla në ditë.";
    } else if (plantId === "6") {
        image.src = "../../Images/Milca.jpg";
        name.textContent = "Milca";
        information.textContent = "VETITË:\n" + "Gjethet e milcës përdoren si sedative, karminative dhe spazmolitike në fryrjet e barkut nga gazët, në katarre të lehta të zorrëve e të stomakut, si dhe për të nxitur rrjedhjen e tëmthit; qetëson neurozat kardiake, rrahjet e forta të zemrës dhe çrregullimet psikoneurotike. Gjethet e milcës përmbajnë esencë me erë karakteristike si të limonit; ato ndihmojnë në prodhimin dhe sekretimin e tëmthit, ngadalësojnë rrahjet e forta të zemrës dhe ulin presionin e ngritur të gjakut, ndihmojnë kundër pagjumësisë me prejardhje nervore e në të gjitha krizat e ngërçet e barkut etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë supe me drogë të grimcuar hidhet në një enë ku shtohen dy gota me ujë të valuar; përmbajtja lihet për t’u ftohur 5–10 minuta, duke e tundur herë pas here; çaji kullohet, ëmbëlsohet sipas dëshirës (me mjaltë ose sheqer); pihen 2–3 gota në ditë.";
    } else if (plantId === "7") {
        image.src = "../../Images/Murrizi.jpg";
        name.textContent = "Murrizi";
        information.textContent = "VETITË:\n" + "Drogat përmbajnë substanca flavonike, aminopurina, adeninë, adenosinë e guaninë dhe krategolaktone, derivate triterpenike (acid ursolik, oleanolik dhe krategolik). Lulja është më e pasur në lëndë vepruese; frutet përmbajnë edhe vitaminë C, B, acid citrik etj. Acidet triterpenike zgjeronjë arteret në përgjithësi dhe arteret koronare në veçanti (që furnizojnë muskulin e zemrës me gjak), dhe fuqizojnë muskulaturën e zemrës. Aminopurinat rregullojnë qarkullimin e gjakut. Drogat kanë veti qetësuese dhe ulin presionin e gjakut. Drogat veprojnë pas një kohe të gjatë. Duke u mbështetur në këto veti, drogat përdoren si mjete antisklerotike, hipotonike dhe sedative për pakësimin e zemrës së dobësuar nga shqetësime nervore, në goditjet e forta të zemrës, në vështirësi frymëmarrjeje, në rastet e presionit të ngritur të gjakut, në pagjumësi, në rastet e dhëmbjeve në zemër, dhe në rritje të ngacmueshmërisë. Drogat përdoren edhe në vështirësitë që shoqërojnë klimakterin. Me rezultate të mira mjekuese ato përdoren në format e lehta të pamjaftueshmërisë së koronareve, në çrregullimet që vijnë nga mos furnizimi i mirë me gjak i trurit, në dëmtimet e zemrës pas sëmundjeve infektive etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Dy lugë çaji drogë të grimcuara (lule ose fryte) hidhen në një enë ku shtohet një filxhan çaji me ujë që zien; ena mbulohet dhe lihet të ftohet; pastaj përmbajtja kullohet dhe lëngu ëmbëlsohet ose jo, sipas dëshirës, dhe pihet. Merren 2–3 doza të tilla në ditë. Drogat e murrizit përdoren edhe në formë tinkture, e cila përgatitet kështu: 20 g lule ose fryte të grimcuara hidhen në një shishe ku shtohen 100 g alkool 60°; përmbajtja pas 10 ditësh kullohet dhe lëngu pihet, 20–25 pika në pak ujë 3 herë në ditë; rregullon të rrahurat e zemrës dhe lehtëson gjumin.";
    } else if (plantId === "8") {
        image.src = "../../Images/Urdhi.jpg";
        name.textContent = "Urdhi";
        information.textContent = "VETITË:\n" + "Droga përmban kryesisht saponinë, glukozidin hederinë, taninë; është vërtetuar edhe prania në të e acidit klorogjenik dhe e jodit; sasia e përbërësve varet nga lloji dhe vendi i rritjes së bimës. Gjethet e freskëta shkaktojnë ngacmimin e lëkurës; në doza të larta ato mund të japin edhe helmime të lehta, ndërsa në doza të vogla zgjerojnë enët e gjakut, në doza të mëdha shkaktojnë të kundërtën, d.m.th. ngushtojnë arteriet dhe njëkohësisht ngadalësojnë rrahjet e zemrës. Gjethet e urdhit lehtësojnë gjithashtu spazmat bronkiale dhe kanë veti antinevralgjike me rezultate të mira në mialgji, parastezike, shiatike, sakroiliake, reumatike, etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Gjysmë luge çaji me drogë të grimcuar hidhen në një enë ku shtohet një filxhan çaji me ujë; përmbajtja zihet 5 minuta, lihet të ftohet dhe kullohet; lëngu pihet gjatë ditës. Nga jashtë, droga përdoret në forma të ndryshme: një grusht me drogë të grimcuar hidhet në një enë ku shtohet 1/2 gotë me uthull; përmbajtja lihet 2 ditë; pak nga kjo lëngë mbështillet me një copë napë dhe vihet mbi pjesët e forcuara të lëkurës ose mbi kallo; disa gjethe të njoma shtypen dhe bëhen në formë qulli, i cili vihet mbi një copë napë e cila shtrihet mbi plagë të ndryshme dhe mbi ulçera varikoze.";
    } else if (plantId === "9") {
        image.src = "../../Images/Vjeshtulla.jpg";
        name.textContent = "Vjeshtulla";
        information.textContent = "VETITË:\n" + "Droga përmban substanca që veprojnë kryesisht në uljen e presionit të gjakut (si p.sh. kolinë, acetilkolinë etj.), substanca që qetësojnë zemrën gjatë çrregullimeve nervore (si viskotoksinë, acid oleanik) etj. Në saje të përbërjes së saj, droga rekomandohet, në radhë të parë, për trajtimin e formave të ndryshme të hipertensionit (hipertension arterial nga ateroskleroza, nga hipertiroidizmi etj.), ku vepron si mjet që largon shenjat e sëmundjes. Në trajtimin e aterosklerozës, vjeshtulla mund të përdoret jo vetëm për të luftuar hipertensionin, por edhe si mjet që pakëson kolesterolin në gjak. Disa autorë kanë provuar se vjeshtulla jep rezultate të mira edhe në hipertensionin e ndërlikuar me nefrit dhe glomerulonefrit, ku janë vënë re përmirësime të theksuara të albuminurisë. Me këtë drogë janë arritur rezultate të mira edhe në albuminurinë e periudhës së shtatzënisë. Vjeshtulla ka edhe veti të nxitë urinimin duke ndikuar, kryesisht, në jashtëqitjen e uresë.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Në familje, droga mund të përdoret kryesisht në formë pluhuri e çaji. Në formë pluhuri përdoret 1–2 g drogë e grimcuar imët tri deri katër herë në ditë. Në formë çaji përgatitet në këtë mënyrë: 8 g drogë të grimcuara imët hidhen në një enë ku shtohet 1/2 litre ujë të ftohtë dhe lihet 1 deri 2 ditë; pas kësaj kohe përmbajtja kullohet dhe çaji përdoret 3–4 herë në ditë në masën një gotë uji; çaji mund të ëmbëlsohet, sipas dëshirës, me sheqer ose mjaltë.";
    } else if (plantId === "10") {
        image.src = "../../Images/Boronica.jpg";
        name.textContent = "Boronica";
        information.textContent = "VETITË:\n" + "Kohët e fundit është provuar se antocianozidet e boronicës kanë veprim e vitaminës P dhe si pasojë janë të dobishme në trajtimin e çrregullimeve të qarkullimit të gjakut që vijnë nga rritja e çarjes së kapilarëve, veçanërisht në hemorragjitë e retinës (të tipit diabetik dhe hipertensiv).\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Frutet merren nga goja në varësi të moshës (mesatarisht 5–10 gram), përtypen dhe gëlltiten. Përdoren edhe në formë çaji duke zier në një gotë me ujë sasinë e frutave të mësipërme, të cilat pasi mufaten, zihen lehtë. Gjethet përdoren gjatë ditës në formë çaji, i cili përgatitet duke zier 2 lugë kafeje me drogë të grimcuar në një enë që përmban një gotë me ujë.";
    } else if (plantId === "11") {
        image.src = "../../Images/Bushi.jpg";
        name.textContent = "Bushi";
        information.textContent = "VETITË:\n" + "Gjethet dhe lëvorja e bushit përmbajnë alkaloide (sidomos bukinë), esencë, tanineti. Kohët e fundit janë izoluar nga bushi një seri alkaloidesh me veti hipotensive. Drogat kanë veti të ulin temperaturën e lartë dhe veti dezinfektuese. Bushi përdoret për uljen, në përgjithësi, të temperaturës së shkaktuar nga pezmatimet e rrugëve të tëmthit dhe të urinës, si dhe për uljen e tensionit të gjakut. Nga jashtë përdoret në sëmundje të lëkurës, në podagrë dhe reumatizëm. Drogat duhet të përdoren vetëm nën mbikëqyrjen e mjekut, sepse janë helmuese; helmimi me këto droga shoqërohet me të vjella, dhëmbje, diarree dhe dispne; në fazën e fundit shfaqen dridhje.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Gjysmë luge kafeje me drogë të copëtuar hidhen në një enë ku shtohet një filxhan çaji me ujë që zien; ena mbulohet me kapak, lihet sa të ftohet, pastaj çaji kullohet dhe ëmbëlsohet sipas dëshirës, e pihet gjatë ditës në 3 doza.";
    } else if (plantId === "12") {
        image.src = "../../Images/Grunamadhi.jpg";
        name.textContent = "Grunamadhi";
        information.textContent = "VETITË:\n" + "Bari dhe lulesat e thara të grunamadhit janë të pasura në lëndë vepruese; ato përmbajnë substanca (siç janë kumarina, melilolina, etj.) që kanë veprim të kundërt me atë të vitaminës K, dhe si pasojë i japin drogës veti që të pengojnë mpiksjen e gjakut. Droga përmban edhe substanca të tjera, siç janë, p.sh., derivatet e purinës (alantoinë, acid alantoinik e urik), pigmentet flavonike, taninet, fitoncidet, etj. Në saje të përbërësve dhe të vetive, droga këshillohet të përdoret gjithnjë, sipas porosisë dhe nën mbikëqyrjen e mjekut, si mjet kundër mpiksjes së gjakut, si qetësues, spazmolitik dhe si mjet kundër pezmatimit dhe etheve. Droga rrit qëndrueshmërinë e enëve të gjakut, duke rritur depërtueshmërinë e tyre; përmirëson qarkullimin e gjakut në tru e në periferi dhe qarkullimin venoz. Droga përdoret edhe nga jashtë, në formë kompresash, për larje, si dhe në formë llapash, si mjet që qetëson, zbut dhe shëron plagë të ndryshme.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "1 lugë çaji me drogë të grimcuar hidhen në një enë ku shtohet 1 filxhan çaji me ujë që zien; përmbajtja lihet 15 minuta në qetësi, pastaj lëngu kullohet dhe pihet i ëmbëlsuar sipas dëshirës; gjatë ditës mund të pihen 2–3 doza të tilla, d.m.th. një sasi çaji që fitohet gjithsej nga 5 g drogë. Çaji më i përqendruar që përgatitet si më sipër, por duke hedhur 2–3 herë më shumë drogë, përdoret nga jashtë, në formë komprese banje, si antiseptik në pezmatimet e syve, për shpëlarjen e plagëve me qelb, si gargare në zhërxhirvitjet, aftet, laringjitet etj. Droga përdoret edhe në formë llape që fitohet duke përzier drogën e grimcuar me ujë të ngrohtë deri sa të kthehet në brumë; ky brumë vihet, me ndihmën e një lecke ose garze, mbi vendin e sëmurë.";
    } else if (plantId === "13") {
        image.src = "../../Images/Angjinare.jpg";
        name.textContent = "Angjinare";
        information.textContent = "VETITË:\n" + "Në saje të cinarinës, glukozideve A dhe B, substancave flavonike të ndryshme etj., gjethet e angjinares përdoren kryesisht në sëmundjet e mëlçisë dhe të veshkave. Droga nxit prodhimin e tëmthit dhe zbrazjen e tij dhe përdoret kundër pezmatimit të rrugëve të tëmthit, vepron në metabolizimin e kolesterinës dhe të urësë dhe nxit urinimin (jashtëqitjen e ujit, klorureve dhe urësë), duke ndihmuar, kështu, në veprimtarinë e veshkave dhe duke lehtësuar urtikariet e të krojturit. Këshillohet në sëmundjet që shoqërohen me rritjen e përqindjes së kolesterinës në gjak dhe veçanërisht në aterosklerozë, ku duhet kombinuar dhe me vitaminë P. Në saje të disa oksidazave që përmban, ul sasinë e sheqerit në gjak dhe jep rezultate të mira në disa forma të diabetit. Rezultate të mira jep edhe në albuminuritë kronike etj., në të cilat vihet re një përmirësim i shfaqjeve albuminurike dhe edematoze.\n\n\n" + "PËRGATITJA DHE PËRDORIMI:\n" + "Në fillim të kurës përdoret 1 lugë gjelle (më vonë dy lugë gjelle) me drogë të grimcuar, e cila zihet 20 deri 30 minuta në një enë që përmban një gotë me ujë. Përmbajtja kullohet; merren 3 doza të tilla në ditë. Kura zgjat rreth 1 muaj, pastaj ndërpritet për 1 muaj dhe rifillohet në rast nevoje.";
    } else if (plantId === "14") {
        image.src = "../../Images/Akja.jpg";
        name.textContent = "Akja";
        information.textContent = "VETITË:\n" + "Veprime koleretike, kolecistokinetike, riostatike, të nxitin prodhimin e tëmthit, urinimin, veti spazmolitike etj.; ato rekomandohen për të shtuar rrjedhjen e tëmthit dhe për të tretur gurët e fshikëzës së tëmthit; lulet e akës përdoren gjithashtu në sëmundjet e rrugëve të frymëmarrjes dhe për të nxitur urinimin etj.; droga e kombinuar edhe me pelin e me bishtamith, bëhet më e efektshme për prodhimin e tëmthit.\n\n\n" + "PËRGATITJA DHE PËRDORIMI:\n" + "Një lugë kafeje me drogë hidhet në një enë ku shtohet një gotë ujë që valon; ena mbulohet me kapak dhe lihet në qetësi 15 minuta. Përmbajtja kullohet; pihen 1 deri 3 doza të tilla në ditë para buke për 10 ditë radhazi.";
    } else if (plantId === "15") {
        image.src = "../../Images/Arrsi.jpg";
        name.textContent = "Arrsi";
        information.textContent = "VETITË:\n" + "Në sajë të substancave tanike e të hidhura, të esencës, saponinave, kolinës etj., droga shton oreksin në grrerje, qetëson gërrimet e stomakut, sekretimin e urinës, nxit prodhimin e tëmthit në mëlçi dhe shëron plagë.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "2–3 lugë gjelle me drogë të grimcuar hidhen në një enë ku shtohet 1 litër ujë që valon; ena mbulohet me kapak, lihet të qëndrojë 1/2 ore, pastaj lëngu kullohet dhe pihet 3–4 herë në ditë nga 1 filxhan kafeje, para buke.";
    } else if (plantId === "16") {
        image.src = "../../Images/Bliri.jpg";
        name.textContent = "Bliri";
        information.textContent = "VETITË:\n" + "Lulet e blirit përmbajnë në mucilagje, esencë të pasur, farnezol, glukozide të ndryshme, sheqerna, tanine dhe substanca të afërta me vitaminë E. Përdoren në gjendje të shkatërruara nga të ftohtit dhe që shoqërohen me temperaturë (rrufë, kollë, gjelbëzë, etj.) në sajë vetisë që kanë për të shkaktuar djersitje; përdoren gjithashtu në sëmundjet e veshkave dhe të fshikëzës urinare, si dhe për të lehtësuar dhëmbjet dhe për të përmirësuar qetësimin e stomakut. Lulet e blirit kanë edhe veti të tjera të ngjashme me ato të lules së shtogut; ato përmirësojnë gjendjen nervore si rrjedhim të gjumën të qetësojnë gjumin.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë supe me lulebliri hidhet në një enë ku shtohet 1 gotë me ujë që valon; ena mbulohet me kapak dhe lihet 5–10 minuta duke e tundur herë pas here, pastaj lëngu kullohet, ëmbëlsohet me sheqer ose me mjaltë dhe pihet i ngrohtë. Merren disa doza të tilla gjatë ditës.";
    } else if (plantId === "18") {
        image.src = "../../Images/Cikorja.jpg";
        name.textContent = "Cikorja";
        information.textContent = "VETITË:\n" + "Gjethet dhe rrënjët e çikores përmbajnë mucilagj, sheqerna, rrëshirë, taninë, inulinë, një glukozid me shije të hidhur të quajtur çikorinë, etj. Në sajë të këtyre lëndëve që përmbajnë, drogat përdoren si mjete që gjallërojnë organizmin, duke përtërirë forcat, që nxitin tretjen dhe urinimin, duke përmirësuar nga njëherë ekzemën, zbrazjen e fshikëzës së tëmthit dhe të dalët jashtë pa acaruar aparatin tretës.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Zihen 1 lugë gjelle me rrënjë ose me gjethe të grimcuara në një xhezve të madhe me ujë dhe gaji kullohet; pihen 2 deri 3 doza të tilla në ditë.";
    } else if (plantId === "19") {
        image.src = "../../Images/Dellinja.jpg";
        name.textContent = "Dëllinja";
        information.textContent = "VETITË:\n" + "Frytet e dëllinjës së zezë përmbajnë sheqerna, vaj miperine, esencë, rrëshirë, etj.; kanë veti të nxisin urinimin dhe të pengojnë zhvillimin e rritjen së mikrobeve në rrugët urinare. Droga konsiderohet si mjet i mirë diuretik që ndihmon në jashtëqitjen e klorureve dhe të azotit në formën e uresë. Këshillohet në hidropizi, në reumatizmin e kyçeve, etj.). Rritja e diurezës fillon pas 4 orësh nga marrja e fryteve dhe vazhdon për po aq orë. Droga sforcon epitelin renal; për këtë arsye nuk këshillohet tek fëmijët dhe në rastet me veshkë të sëmurë të pirur për hematuri, albuminuri etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:" + "1 lugë kafeje me drogë të grimcuar zhy tet në një gotë me ujë; ena mbulohet me kapak dhe përmbajtja zihet 5–10 minuta, lihet në qetësi derisa të ftohet dhe më pas kullohet dhe lëngu pihet. Merren 2–3 doza të tilla në ditë.";
    } else if (plantId === "20") {
        image.src = "../../Images/Dydhëmbëshi_tripjesësh.jpg";
        name.textContent = "Dydhëmbëshi tripjesësh";
        information.textContent = "VETITË:\n" + "Droga, d.m.th. bari i mbledhur në kohën e fillimit të lulëzimit të bimës dhe i tharë, në saje të glukozideve flavonike, vitaminës C, sheqernave, esencës, karotinës, manganezit, etj. që përmban, ka veti të shtojë urinimin dhe djersitjen, të përmirësojë tretjen dhe të ndikojë në normalizimin e metabolizmit. Në saje të këtyre vetive, kjo drogë këshillohet në gurët e veshkave dhe në çrregullimet e fshikëzës së urinës, kundër hemorragjive të brendshme, kur është i nevojshëm shtimi i të urinuarit dhe i djersitjes etj.\n\n\n" + "PËRGATITJA E PËRDORIMIT:\n" + "Dy deri katër lugë supe me drogë të grimcuar hidhen në një enë të cinkuar ku shtohet një litër me ujë të zier; përmbajtja lihet të qëndrojë 15 minuta në enë të mbuluar me kapak. Pastaj lëngu kullohet; prej këtij lëngu të rriturit mund të pinë dy-tre gota, kurse fëmijët dy-tre filxhanë në ditë.";
    } else if (plantId === "21") {
        image.src = "../../Images/Grami.jpg";
        name.textContent = "Grami";
        information.textContent = "VETITË:\n" + "Në saje të glucideve, esencës etj., droga nxit urinimin, duke ndihmuar veprimtarinë e veshkave dhe përdoret si mjet që pastron organizmin. Këshillohet përdorimi në pezmatimin e pjesëve të poshtme të rrugëve urinare, në reumatizëm dhe sëmundje të lëkurës. Krahas këtyre veprimeve, rizoma e gramit ndihmon në mjekimin e hipertensionit arterial dhe mund të përdoret me dobi si vetëm, ashtu dhe e kombinuar me gjethe ulliri, me gjethe rozmarine, me degë vjeshtulli etj. Në saje të triticines së ngjashme me inulinën, droga përdoret si ndihmëse në sëmundjen e diabetit.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë supe me drogë të thërrmuar (5 g) futet në një enë ku shtohet një gotë me ujë (150–200 g) dhe zihet 10 minuta, pastaj çaji kullohet dhe pihet i ëmbëlsuar me sheqer ose mjaltë, sipas dëshirës. Gjatë ditës merren 2 ose 3 doza të tilla." ;
    } else if (plantId === "22") {
        image.src = "../../Images/Fshesa_e_kuqe.jpg";
        name.textContent = "Fshesa e kuqe";
        information.textContent = "VETITË:\n" + "Droga përmban esencë me erë të këndshme, tanine, koline, etj.; nuk është studiuar sa duhet nga ana e veprimit; dihet se nxit epitelin e veshkës dhe si pasojë shton nxjerrjen e acidit urik (mendohet se ky veprim nuk i kushtohet lëndëve vepruese të vetë bimës, por produkteve të zbërthimit të tyre); bima ka edhe veti të ndalojë rrjedhjen e gjakut (hemostatike) dhe veti të nxitë formimin e rruazave të bardha të gjakut. Këshillohet si mjet hemostatik dhe diuretik në hemorragji, në heqje barku me gjak dhe në proceset pezmatimi të rrugëve urinare. Esenca e bimës vepron kundër parazitëve të zorrëve dhe askarideve.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "5 lugë kafeje me drogë të grimcuar hidhen në një enë, ku shtohet 1 filxhan me ujë; përmbajtja zihet për 5 minuta, lihet të ftohet, kullohet, ëmbëlsohet sipas dëshirës dhe pihet; merren 3 doza të tilla në ditë.";
    } else if (plantId === "23") {
        image.src = "../../Images/Gerdeci.jpg";
        name.textContent = "Gërdeci";
        information.textContent = "VETITË:\n" + "Gjethet e gërdecit, në sajë të heterozideve arbutinë e metilarbutinë, tanineve, flavoneve dhe lëndëve fungicide, përdoren si mjet që pengon zhvillimin dhe rritjen e mikroorganizmave në rrugët urinare. Arbutina dhe metilarbutina, në kushte të caktuara, ndryshohen në fenole (hidrokinon dhe metilhidrokinon) që kanë veti dezinfektuese; ky ndryshim ngjet, në radhë të parë, në rrugë urinare të pezmatara dhe jo në organe të shëndosha. Në sëmundje të aparatit urinar ato mund të përdoren vetëm atëherë kur urina është bazike; kjo gjë mund të arrihet duke përdorur njëkohësisht bikarbonat natriumi për të forcuar veprimin e drogës në rastet e infeksioneve me bakteret e grupit koli, si dhe në rastet kur urina është acide. Mjekimi duhet të kontrollohet nga mjeku, sepse në doza të larta droga mund të shkaktojë glukozuri dhe të dëmtojë mëlçinë. Droga hyn në përbërjen e çajrave diuretike. Sasia e lartë e tanineve në drogë, kur kjo përdoret për kohë të gjatë, mund të shkaktojë kapsllëk.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Dy lugë çaji me drogë të grimcuar (baraz me 5,5 g) hidhen në një enë ku shtohet gjysmë gote me ujë që zien; përmbajtja lihet në qetësi për 30 minuta, pastaj lëngu kullohet. Çaji që fitohet, pihet 2–3 herë gjatë ditës i ëmbëlsuar sipas dëshirës. Nuk këshillohet përgatitja e çajit me zierje, sepse në këtë rast ai del më i hidhur dhe me pak i efektshëm. Droga mund të përdoret edhe në formë pluhuri; merren 3–4 herë nga 2 g në ditë.";
    } else if (plantId === "24") {
        image.src = "../../Images/Gjarpri_mjeksor.jpg";
        name.textContent = "Gjarpri mjeksor";
        information.textContent = "VETITË:\n" + "Droga që përmban taninë, acide organike, etj., ka veti qetësuese, ndihmëse kundër kollës dhe acarimeve të rrugëve të frymëmarrjes, djersitëse dhe nxit kryesisht urinimin (diuretike) tek të sëmurë që vuajnë nga mbajtja e vazhdueshme e urinës nga prania, në këtë të fundit, e oksalateve dhe e acidit oksalik.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "20 g drogë e grimcuar zihen për 30 minuta në një gotë me ujë në enë të mbyllur me kapak, lihen në qetësi 15 minuta dhe pastaj çaji që fitohet kullohet e pihet gjatë ditës i ëmbëlsuar (ose dhe i aromatizuar me pak esencë mendër ose anasoni).";
    } else if (plantId === "25") {
        image.src = "../../Images/Bar_i_majasellit.jpg";
        name.textContent = "Bar i majasellit";
        information.textContent = "VETITË:\n" + "Bari i majasellit, në sajë të tanineve, esencës etj., rekomandohet në mjekimin e majasellit dhe të kolitit.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Merren rreth 3 tufa (ose 45 g) bar majaselli, zihen në 1 kg ujë për 1½ orë, lëngu kullohet dhe prej tij pihen 3 filxhana në ditë; kura vazhdon rreth 7 deri 20 ditë për majasellin dhe rreth 20–30 ditë për kolitin.";
    } else if (plantId === "26") {
        image.src = "../../Images/Bershelliza.jpg";
        name.textContent = "Bërshëlliza";
        information.textContent = "VETITË:\n" + "Droga përmban rrëshirë me veti të forta laksative, tanine dhe lëndë me natyrë gomoze; nxit muskulaturën e lëmuar, hyn në mjetet terapeutike që shpejtojnë peristaltikën e zorrëve dhe rrisin rrjedhjen e tëmthit. Bari i bërshëlizës është laksativ i fortë e kolagog dhe duhet përdorur me kujdes.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "1 lugë çaji me drogë të grimcuar hidhet në një enë ku shtohet 1 filxhan çaji me ujë që zien; përmbajtja lihet për 15 minuta, pastaj lëngu kullohet dhe pihet.";
    } else if (plantId === "27") {
        image.src = "../../Images/Borziloku.jpg";
        name.textContent = "Borziloku";
        information.textContent = "VETITË:\n" + "Në sajë të esencës (me estragol, linalol, etj.) e të tanineve që përmban, bari i bimës ka veti të përmirësojë aktivitetin e stomakut, të pakësojë gazët në zorrë e të hapë oreksin, të lirojë ngërçin e muskulaturës së zorrëve. Përdoret si qetësues i dhembjeve të barkut, si aromatizues, kundër pezmatimit kronik të stomakut, çrregullimeve të tubit tretës, kapsllëkut që vjen nga ngërçi (tkurrja, shtrëngimi) i muskulaturës së zorrës etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Dy lugë çaji me drogë të grimcuar hidhen në një enë të zinkuar, ku shtohet 1 gotë me ujë që zien; ena mbulohet me kapak dhe lihet për 10–15 minuta duke e tundur herë pas here; pastaj lëngu kullohet, ëmbëlsohet ose jo me sheqer apo me mjaltë dhe pihet. Gjatë ditës mund të merren 2–3 doza të tilla.";
    } else if (plantId === "28") {
        image.src = "../../Images/Drunakuqi.jpg";
        name.textContent = "Drunakuqi";
        information.textContent = "VETITË:\n" + "Droga përmban glukozide antrakinonike, të cilat kanë veti laksative purgative, sidomos në kapsllëk kronik. Droga ka veti të nxitë sekretimin e tëmthit dhe të veprojë në zorrën e trashë. Në kapsllëkun e shkaktuar nga pamjaftueshmëria e lëngut të tëmthit këshillohet kombinimi i drunakuqit me droga të tjera siç janë gjethet e senës, rrënjët e çikores dhe të radhigjes, gjethet e angjinares etj.; rezultate të mira ato japin edhe kundër majmërise.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë gjelle me drogë të grimcuar hidhen në një enë ku shtohet një gotë me ujë; përmbajtja lihet në qetësi 15 minuta dhe pastaj zihet për 10 minuta. Në vazhdim lëngu lihet deri sa ftohet dhe kullohet; pihet i ngrohur në mbrëmje, para gjumit. Në kapsllëkun e fortë doza e mësipërme përsëritet edhe në mëngjes esëll. Droga përdoret edhe në formë pluhuri: në këtë rast merren 1 deri 3 g në ditë.";
    } else if (plantId === "29") {
        image.src = "../../Images/Fomi_mjeksor.jpg";
        name.textContent = "Fomi mjeksor";
        information.textContent = "VETITË:\n" + "Në sajë të alkaloideve helmuese të fomnit (proto­pinë, etj.), të substancave të hidhura, acidit fumarik, droga vepron në muskulaturën e lëmuar duke shpejtuar peristaltikën e zorrëve dhe duke nxitur urinimin, djersitjen dhe rrjedhjen e tëmthit. Ndihmon metabolizmin dhe përmirëson punën e stomakut, këshillohet edhe në çrregullimet e tëmthit. Në sajë të këtyre vetive përdoret në sëmundje të mëlçisë dhe të fshikëzës së tëmthit, në heqjet e barkut nga çrregullime të tretjes, në kapsllëk dhe në sëmundje që karakterizohen nga mbajtja e ujit në organizëm. Acidi fumarik, sipas të dhënave të fundit, ndihmon proceset e oksidimit në organizëm.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Dy lugë kafeje (2,5 g) drogë e grirë hidhen në një enë të zinkuar ku përvëlohen me 1 gotë me ujë që zien; ena mbulohet me kapak dhe lihet 10–15 minuta; pastaj çaji kullohet dhe pihet në dy doza gjatë ditës.";
    } else if (plantId === "30") {
        image.src = "../../Images/Arrsi.jpg";
        name.textContent = "Arrsi";
        information.textContent = "VETITË:\n" + "Në sajë të substancave tanike e të hidhura, të esencës, saponinave, kolinës etj., droga shton oreksin në grrerje, qetëson gërrimet e stomakut, sekretimin e urinës, nxit prodhimin e tëmthit në mëlçi dhe shëron plagë.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "2–3 lugë gjelle me drogë të grimcuar hidhen në një enë ku shtohet 1 litër ujë që valon; ena mbulohet me kapak, lihet të qëndrojë 1/2 ore, pastaj lëngu kullohet dhe pihet 3–4 herë në ditë nga 1 filxhan kafeje, para buke.";
    } else if (plantId === "31") {
        image.src = "../../Images/Bar_gjaku.jpg";
        name.textContent = "Bar gjaku";
        information.textContent = "VETITË:\n" + "Droga ka veti të ndryshme, në sajë të substancave që përmban. Kështu, p.sh., në sajë të tanineve dhe të esencës, droga jep rezultate të mira në diarre që shoqërohen me një humbje të tonusit (të shtrëngimit) të zorrëve, kurse në sajë të mucilagjeve ka edhe veti qetësuese. Është provuar se, në sajë të salikarines (heterozid), droga ka edhe veti që të ndalojë rrjedhjen e gjakut (hemorragjinë), të rrudhë brenda një kohe të shkurtër mukozën e zorrëve, si dhe veti specifike më dizinfektuese rinë bacilare. Droga ka edhe veti të lehta antibiotike. Në rastet të përshkruara më lart, rekomandohet edhe në gastroenterit, në tifo dhe në dizanteri.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "30 ose 40 g drogë e grimcuar hidhen në një enë të zingjar ku përvëlohen me 1 litër ujë që zien; ena mbulohet me kapak dhe lihet për 15 minuta sa të ftohet, pastaj çaji kullohet nëpërmjet një nape. Pihen 300 deri 500 g çaj në ditë.";
    } else if (plantId === "32") {
        image.src = "../../Images/Bishtamithi.jpg";
        name.textContent = "Bishtamithi";
        information.textContent = "VETITË:\n" + "Në sajë të esencës (me azulen, cineol, etj.), substancës së hidhur akiliene, vitaminës K, tanineve, etj., që përmban, droga përdoret si mjet që çliron spazmat e muskulaturës së butë (spazmolitik), veçanërisht të mitrës, ngërçet (dhimbjet, spazmat) e stomakut (me origjinë nervore) të grave, si rregullues dhe lehtësues i menstruacioneve, në mjekimin e majasëllit, kundër heqjes së barkut, si antiinflamator në acarimet e gojës, fytit, në djegie, etj. Meqenëse rrit aftësinë e gjakut për t’u mpiksur, përdoret për ndërprerjen e rrjedhjes së gjakut si p.sh. në hemorragjitë e mushkërive, të veshkave, në menstruacione të mëdha, si dhe për mjekimin e anemive sekondare të ndryshme; këshillohet edhe kundër kolitës. Përdorimi për një kohë të gjatë i drogës jep pështjellim, turbullim dhe dhëmbje koke.\n\n\n" + "PËRGATITJA E PËRDORIMIT:\n" + "Një lugë supe me drogë të grimcuar hidhet në një enë ku shtohet 1 gotë me ujë; ena mbulohet me kapak dhe përmbajtja zihet për 5 minuta; pastaj çaji kullohet dhe pihet i paëmbëlsuar; gjysmë ore para buke; merren dy doza të tilla në ditë. Për përdorim të jashtëm, në formë banjash për mjekimin e plagëve të qelbëzuara, të sëmundjeve të lëkurës, mishrave të dhëmbëve etj., përdoret çaji që përgatitet si më sipër, por duke përdorur 2 lugë gjelle me drogë për një gjysmë gote me ujë. Për mjekimin e ulcerave varikoze, të majasëllit, morrthit, etj., përdoret lëngu i shtrydhur i bimës së freskët.";
    } else if (plantId === "33") {
        image.src = "../../Images/Boronica.jpg";
        name.textContent = "Boronica";
        information.textContent = "VETITË:\n" + "Kohët e fundit është provuar se antocianozidet e boronicës kanë veprim e vitaminës P dhe si pasojë janë të dobishme në trajtimin e çrregullimeve të qarkullimit të gjakut që vijnë nga rritja e çarjes së kapilarëve, veçanërisht në hemorragjitë e retinës (të tipit diabetik dhe hipertensiv).\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Frutet merren nga goja në varësi të moshës (mesatarisht 5–10 gram), përtypen dhe gëlltiten. Përdoren edhe në formë çaji duke zier në një gotë me ujë sasinë e frutave të mësipërme, të cilat pasi mufaten, zihen lehtë. Gjethet përdoren gjatë ditës në formë çaji, i cili përgatitet duke zier 2 lugë kafeje me drogë të grimcuar në një enë që përmban një gotë me ujë.";
    } else if (plantId === "34") {
        image.src = "../../Images/Bushi.jpg";
        name.textContent = "Bushi";
        information.textContent = "VETITË:\n" + "Gjethet dhe lëvorja e bushit përmbajnë alkaloide (sidomos bukinë), esencë, tanineti. Kohët e fundit janë izoluar nga bushi një seri alkaloidesh me veti hipotensive. Drogat kanë veti të ulin temperaturën e lartë dhe veti dezinfektuese. Bushi përdoret për uljen, në përgjithësi, të temperaturës së shkaktuar nga pezmatimet e rrugëve të tëmthit dhe të urinës, si dhe për uljen e tensionit të gjakut. Nga jashtë përdoret në sëmundje të lëkurës, në podagrë dhe reumatizëm. Drogat duhet të përdoren vetëm nën mbikëqyrjen e mjekut, sepse janë helmuese; helmimi me këto droga shoqërohet me të vjella, dhëmbje, diarree dhe dispne; në fazën e fundit shfaqen dridhje.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Gjysmë luge kafeje me drogë të copëtuar hidhen në një enë ku shtohet një filxhan çaji me ujë që zien; ena mbulohet me kapak, lihet sa të ftohet, pastaj çaji kullohet dhe ëmbëlsohet sipas dëshirës, e pihet gjatë ditës në 3 doza.";
    } else if (plantId === "35") {
        image.src = "../../Images/Luleshtrydhe.jpg";
        name.textContent = "Luleshtrydhja";
        information.textContent = "VETITË:\n" + "Gjethet e thara të luleshtrydhes, në sajë të substancave që përmbajnë (tanine, pak esencë me aromë limoni, vitaminë C, kripëra minerale, acid malik e salicilik etj.), përdoren në infeksionet e mukozës së zorrëve që shoqërohen me rrjedhje barku, në sëmundjet e veshkave dhe kundër gurëve të aparatit urinar, si dhe në rastet e urinimit me gjak. Nga jashtë, lëngu i drogës rekomandohet për kompresa në hemorroide të gjakosura, për shpëlarjen e zgavrës së gojës së infektuar dhe me erë të keqe, për mjekimin e ekzemës etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Në rastet e rënda të heqjes së barkut rekomandohet zierja e 100 deri 300 gjetheve të njoma (ose e 20 deri 60 g gjethe të thata) në 1 litër ujë; lëngu kullohet dhe pihet me lugë gjelle çdo 1 orë.";
    } else if (plantId === "36") {
        image.src = "../../Images/Manaferra.jpg";
        name.textContent = "Manaferra";
        information.textContent = "VETITË:\n" + "Gjethet e thara të manaferres që përmbajnë tanine, inozit, acide organike etj., përdoren në formë çaji kundër hemorragjive të brendshme, heqjes së barkut dhe hemorroideve. Çaji që përgatitet me gjethet e manaferres përdoret në formë gargare kundër mahisjes së fytit, faringjitit, aftës dhe acarimit të mishrave të dhëmbëve.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Dy lugë kafeje me drogë të grimcuar zihen 15 minuta në një gotë me ujë; çaji lihet në qetësi për një farë kohe, pastaj kullohet; pihen 2–3 doza të tilla në ditë.";
    } else if (plantId === "37") {
        image.src = "../../Images/Metriku.jpg";
        name.textContent = "Metriku";
        information.textContent = "VETITË:\n" + "Droga përmban alkaloide, karoten, vitaminë C, saponine, tanine, pektinë, derivate flavonike, etj. Ndërmjet alkaloideve që janë izoluar deri më sot nga kjo drogë, më kryesoret janë vinkamajoridina, vinkamajina, rezepina, etj. Ka autorë që kanë provuar se metrikë ka veti të ngjashme me ato të bimës Vinca minor L., e cila nuk është takuar në vendin tonë. Në sajë të tanineve, ekstraktet e drogës kanë veti hemostatike e rrudhëse; ato përdoren edhe për të pakësuar ngacmimin e kollës. Alkaloidet ulin presionin e lartë të gjakut. Në formë çaji, droga ndikon në ndalimin e hemorragjive me origjinë të ndryshme, si p.sh. në rrjedhjet e gjakut nga hunda, mishrat e dhëmbëve, organet gjenitale. Përdoret në pezmatimet e mukozës së zgavrës së gojës dhe në pezmatimet e bronkeve dhe të mushkërive. Po në formë çaji, bari i mëtrikut përdoret nga populli kundër pezmatimit të aparatit të tretjes dhe të aparatit genitourinar; përdoret nga gratë për pakësimin e qumështit të gjirit. Nga jashtë droga përdoret në formë valese (dekokt) për mjekimin e acarimeve të gojës e të fytit (si gargërizëm), si dhe për shërimin e ekzemës e të sëmundjeve të tjera të lëkurës.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë çaji me drogë të grimcuar hidhet në një enë ku shtohet një filxhan me ujë që zien dhe përmbajtja lihet 15 minuta; pastaj ajo kullohet dhe lëngu ëmbëlsohet sipas dëshirës e pihet; merren 2 doza të tilla në ditë.";
    } else if (plantId === "38") {
        image.src = "../../Images/Bliri.jpg";
        name.textContent = "Bliri";
        information.textContent = "VETITË:\n" + "Lulet e blirit përmbajnë në mucilagje, esencë të pasur, farnezol, glukozide të ndryshme, sheqerna, tanine dhe substanca të afërta me vitaminë E. Përdoren në gjendje të shkatërruara nga të ftohtit dhe që shoqërohen me temperaturë (rrufë, kollë, gjelbëzë, etj.) në sajë vetisë që kanë për të shkaktuar djersitje; përdoren gjithashtu në sëmundjet e veshkave dhe të fshikëzës urinare, si dhe për të lehtësuar dhëmbjet dhe për të përmirësuar qetësimin e stomakut. Lulet e blirit kanë edhe veti të tjera të ngjashme me ato të lules së shtogut; ato përmirësojnë gjendjen nervore si rrjedhim të gjumën të qetësojnë gjumin.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë supe me lulebliri hidhet në një enë ku shtohet 1 gotë me ujë që valon; ena mbulohet me kapak dhe lihet 5–10 minuta duke e tundur herë pas here, pastaj lëngu kullohet, ëmbëlsohet me sheqer ose me mjaltë dhe pihet i ngrohtë. Merren disa doza të tilla gjatë ditës.";
    } else if (plantId === "39") {
        image.src = "../../Images/Dellinja.jpg";
        name.textContent = "Dëllinja";
        information.textContent = "VETITË:\n" + "Frytet e dëllinjës së zezë përmbajnë sheqerna, vaj miperine, esencë, rrëshirë, etj.; kanë veti të nxisin urinimin dhe të pengojnë zhvillimin e rritjen së mikrobeve në rrugët urinare. Droga konsiderohet si mjet i mirë diuretik që ndihmon në jashtëqitjen e klorureve dhe të azotit në formën e uresë. Këshillohet në hidropizi, në reumatizmin e kyçeve, etj.). Rritja e diurezës fillon pas 4 orësh nga marrja e fryteve dhe vazhdon për po aq orë. Droga sforcon epitelin renal; për këtë arsye nuk këshillohet tek fëmijët dhe në rastet me veshkë të sëmurë të pirur për hematuri, albuminuri etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:" + "1 lugë kafeje me drogë të grimcuar zhy tet në një gotë me ujë; ena mbulohet me kapak dhe përmbajtja zihet 5–10 minuta, lihet në qetësi derisa të ftohet dhe më pas kullohet dhe lëngu pihet. Merren 2–3 doza të tilla në ditë.";
    } else if (plantId === "40") {
        image.src = "../../Images/lulekuqe.jpg";
        name.textContent = "Lulekuqe";
        information.textContent = "VETITË:\n" + "Droga përmban kryesisht alkaloidin readinë, substanca mucilaginoze, pigment antocianik etj. Në alkaloidet e saj nuk ka morfinë. Droga ka veti të qetësojë qendrën e frymëmarrjes, të qetësojë kollën dhe të mënjanojë ngacmimin e saj, të përmirësojë dhe të lehtësojë kollitjen. Këshillohet si ekspektorante në ftohje, në pezmatimin e rrugëve të frymëmarrjes, kryesisht tek fëmijë me pezmatim të bronkeve dhe me sëmundje të mushkërive.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "1/2–2 lugë çaji hidhen në një enë ku përvëlohen me 1/2 gotë ujë që zien; ena mbulohet me kapak dhe lihet gjysmë ore; pastaj lëngu kullohet dhe pihet i ëmbëlsuar sipas dëshirës. Pihen 1–3 doza të tilla në ditë.";
    } else if (plantId === "41") {
        image.src = "../../Images/Luledele.jpg";
        name.textContent = "Luledele";
        information.textContent = "VETITË:\n" + "Në sajë të saponineve, esencës, mucilagjeve, tanineve, antoksantinës, pigmenteve flavonike etj., droga, në sajë të vetive rrudhëse edhe ekspektorante të lehta, këshillohet në sëmundje të mushkërive dhe në pezmatime të rrugëve të sipërme të frymëmarrjes.\n\n\n" + "PËRGATITJA E PËRDORIMIT:\n" + "Një lugë çaji me drogë hidhet në një enë ku përvëlohet me gjysëm gote me ujë që zien. Ena mbulohet me kapak, lihet 15 minuta, pastaj përmbajtja kullohet.";
    } else if (plantId === "42") {
        image.src = "../../Images/Lulebasani.jpg";
        name.textContent = "Lulebasani";
        information.textContent = "VETITË:\n" + "Në sajë të esencës, pigmenteve, rrëshirës dhe tanineve që përmban, bima është shumë e dobishme, sepse pengon zhvillimin dhe rritjen e mikrobeve (antiseptik) në plagë, puçrra dhe djegie; në këto raste këshillohet vaji i lulebasanit për përdorim të jashtëm që fitohet duke maceruar drogën (shih më poshtë). Veç kësaj, droga e përdorur nga goja, është e efektshme në proceset metabolike, në sëmundjet e traktit tretës, të mëlçisë, të tëmthit, në hemorragjitë e traktit tretës dhe të mushkërive, në pagjumësi dhe në sëmundje të veshkave. Ajo përmirëson qarkullimin e gjakut dhe qetëson gjendjet me tension nervor. Në sajë të këtyre vetive, lulebasani përdoret si mjet sedativ, antiflogjistik dhe diuretik i lehtë në sëmundje të traktit tretës që vijnë nga pamjaftueshmëri e aktivitetit të stomakut, mëlçisë dhe tëmthit, në gjendje ngacmimi e ankthi, në rastet e gjumit të çrregullt, si dhe në sëmundje të veshkave. Mjekësia jonë popullore këshillon përdorimin e drogës për mjekimin e gastritit dhe të ulcerave të stomakut dhe të duodenit. Prania e pigmentit të kuq hipericinë që lokalizohet në gjendra me ngjyrë të zezë në lule e gjethe të lulebasanit, i jep bimës veti fotosensibilizuese: kafshët me qime të bardha (dele, kuaj, gjedh) që hanë bimën dhe ndërkohë qëndrojnë në diell, goditen nga e ashtuquajtura «sëmundje e dritës», e cila shoqërohet me pezmatimin e lëkurës dhe të mukozave, me kruarje dhe çrregullime të tjera që mund ta çojnë kafshën deri në ngordhje.\n\n\n" + "PËRGATITJA E PËRDORIMIT:\n" + "Një lugë gjelle me drogë të thërmuar zhytet në dy ose tri gota me ujë, zihet për 5–10 minuta dhe pastaj, pas një farë kohe, çaji që fitohet kullohet dhe pihet gjatë ditës. Mjekësia jonë popullore këshillon përgatitjen e bimës për mjekimin e djegieve, të plagëve dhe të hemorroideve në këtë mënyrë: 500 g bar lulebasani të freskët dhe të copëtuar zhytet në përzierjen e përbërë nga 1000 g vaj ulliri dhe 500 g verë të bardhë dhe lihen në qetësi 3 ditë. Pastaj përzierja ngrohet në një banjë uji (mbi ujë të valuar dhe jo drejtpërdrejt në zjarr) në një enë të gjerë deri sa vera të avullohet tërësisht. Mbetja vajore me ngjyrë si në të kuqe ruhet në shishe të vogla (10–20 g) të mbyllura mirë dhe përdoret në formë kompresash, duke vendosur copa pëlhure të njomura me vaj mbi sipërfaqet e dëmtuara të lëkurës (ka veprim qetësues lokal, të lehtë, por të vazhdueshëm, pakëson reaksionet e acarimit, ndihmon ripërtëritjen e indeve).";
    } else if (plantId === "43") {
        image.src = "../../Images/MUllaga.jpg";
        name.textContent = "Mullaga";
        information.textContent = "VETITË:\n" + "Rrënja përmban me shumicë mucilagje e pektina, amidon, sheqerna etj. dhe përdoret me sukses kundër pezmatimit të rrugëve të frymëmarrjes dhe të fytit, për të lehtësuar nxjerrjen e gëlbazës dhe, nga jashtë, për të shpëlarë fytin dhe hundën. Në përgjithësi, si rrënja, ashtu dhe gjethet, përdoren si mjete ndihmëse, në pezmatimet e mukozës së organeve të frymëmarrjes dhe në astmën bronkiale. Drogat këshillohen gjithashtu në pezmatime të rrugëve urinare dhe të zorrëve, si dhe në diarre, veçanërisht në heqjet e forta të barkut tek fëmijët.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Këshillohet që çaji të përgatitet me rrugë të ftohtë. Për këtë qëllim, 1 lugë gjelle me rrënjë ose gjethe të thata e të prera hidhen në një enë ku shtohet 1 gotë me ujë; përzierja lihet 6 orë, pastaj përmbajtja kullohet dhe lëngu ëmbëlsohet sipas dëshirës. Çaji i freskët pihet në doza të tilla disa herë në ditë. Për shpëlarjen e fytit ose për gargare përdoret gjithashtu çaji i freskët, disa herë në ditë.";
    } else if (plantId === "44") {
        image.src = "../../Images/Majdanozi_i_eger.jpg";
        name.textContent = "Majdanozi i eger";
        information.textContent = "VETITË:\n" + "Në sajë të përbërjes së saj, droga ka veti të nxjerrë gëlbazën nga mushkëritë, bronket dhe trakeja. Këshillohet si lëngëzuese dhe nxjerrëse e gëlbazës, në sëmundjet e rrugëve të frymëmarrjes, si, p.sh., në përzënimin e bronkeve, në kollë dhe në sëmundje nga të ftohurit.\n\n\n" + "PËRGATITJA E PËRDORIMIT:\n" + "Një lugë çaji me drogë të grimcuar hidhet në një enë, ku shtohet një gotë me ujë që zien; ena mbulohet me kapak dhe lihet 15 minuta, duke e përzier herë pas here; pastaj përmbajtja kullohet dhe lëngu pihet i ngrohtë dhe i ëmbëlsuar. Merren 1 deri 3 doza të tilla në ditë.";
    } else if (plantId === "45") {
        image.src = "../../Images/thundermushka.jpg";
        name.textContent = "Thundermushka";
        information.textContent = "VETITË:\n" + "Në sajë të substancave mucilaginoze, të esencës dhe të fitoncideve, gjethet dhe lulet e thara të thundërmushkës qetësojnë kollën e lehtësojnë nxjerrjen e gëlbazës në katarret akute të rrugëve të frymëmarrjes, jo në periudhën e inflamacionit fillestar, por në fazën e shtimit të sekrecioneve dhe ndihmojnë në rralimin e në lehtësimin e krizave të astmës. Përdoren edhe kundër gripit të rëndë dhe kollës së vazhdueshme. Gjethet kanë veprim të lehtë diuretik. Veçanërisht të efektshme janë llapat me gjethe të freskëta kundër dhembjeve të kyçeve, reumatizmit, podagrës, goditjeve të kyçeve dhe sëmundjeve kronike të kyçeve zakonisht me karakter distrofik (artrozë). Mbi përdorimin e llapave, shih më poshtë.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë supë me drogë gjethe të thërrmuara (5 g) zhytet në një gotë me ujë (150–200 g) dhe zihet 5 minuta; pastaj çaji kullohet dhe pihet i ngrohtë, i ëmbëlsuar sipas dëshirës, me mjaltë ose me sheqer.";
    } else if (plantId === "46") {
        image.src = "../../Images/gjemb_gomari.jpg";
        name.textContent = "Gjemb gomari";
        information.textContent = "VETITE:\n" + "Farat përmbajnë një substancë të hidhur, esencë, glikozide dhe amina biogjene (si tiraminë, histaminë, etj.), kanë veti të rrisin sasinë e lëngjeve tretëse (lëngjet e stomakut dhe të tëmthit), të përmirësojnë punën e mëlçisë, të ulin temperaturën e lartë dhe të dobësojnë veprimet e sistemit nervor simpatik. Përdoren si koleretikë, kolagogë dhe qetësues në sëmundjen e të verdhëzës, në sëmundje të mëlçisë, në sëmundje të tëmthit, në gurët e tëmthit, në pezmatime të mëlçisë dhe në cirrozë. Është provuar se droga është e efektshme edhe kundër të gjitha dëmtimeve parenkimatoze të mëlçisë, ku frytet jepen si mjet ndihmës krahas dietës së përshtatshme dhe kamoterapisë. Nga jashtë droga përdoret për mjekimin e majasëllit, në ngërçe të venave etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Droga mund të përdoret në formë pluhuri duke marrë 4–5 herë në ditë nga 1 lugë çaji me fara të pluhurosura. Droga përdoret edhe në formë çaji që përgatitet kështu: 1 lugë çaji me fryte të copëtuara hidhen në një enë ku përvëlohen me gjysmë gote me ujë të zier; ena mbulohet me kapak dhe lihet në qetësi 15 minuta; lëngu kullohet dhe pihet; merren 2–3 doza të tilla në ditë.";
    } else if (plantId === "47") {
        image.src = "../../Images/Gjethe_delli.jpg";
        name.textContent = "Gjethedelli";
        information.textContent = "VETITË:\n" + "Gjethet e gjithedellit përmbajnë heterozidin aukubin, enzime, tanine, ksantofil, por kryesisht substanca mucilagjinoze e pektinike, në sajë të të cilave ato përdoren për të provokuar nxjerrjen e gëlbazës (ekspektorant) dhe si ndihmesë për të mjekuar katarret e rrugëve të frymëmarrjes, bronkitin, astmën etj. Të përdorura nga jashtë, gjethet e gjithedellit kanë veti dregëzuese (mbyllje plagësh të ndryshme, puçrrash varikoze etj.); gjethet në formë çaji rekomandohen për gargare në rastet e acarimit të bajameve, për larjen e syve (në acarimet e konjuktivës) etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë supe me drogë të grimcuar hidhet në një enë ku shtohet një gotë me ujë; përmbajtja lihet 1 orë që të bymehet, pastaj zihet për 10–15 minuta, kullohet dhe çaji që fitohet pihet. Pihen dy tri gota në ditë.";
    } else if (plantId === "48") {
        image.src = "../../Images/Pisha.jpg";
        name.textContent = "Pisha";
        information.textContent = "VETITË:\n" + "Sythet e pishës përmbajnë esencë (të pasur me pinene), rrëshirë, tanine, vitaminë C, K, etj., karotinë, glukozide etj. Në saje të kësaj përmbajtjeje, droga përdoret si zbutëse e pezmatimit të rrugëve të frymëmarrjes (kollë, bronkit, etj.) dhe si mjet diuretik që këshillohet në pielit, cistit e uretrit. Nga jashtë sythet e pishës përdoren në banja me veprim antiseptik e cikatrizues.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë kafeje me sythe hidhen në një enë ku shtohet një gotë me ujë që zien; ena mbulohet me kapak, lihet 15 minuta dhe pastaj përmbajtja kullohet dhe lëngu pihet 2 deri 3 doza të tilla të ngrohta gjatë ditës.";
    } else if (plantId === "49") {
        image.src = "../../Images/Sherbela.jpg";
        name.textContent = "Sherbela";
        information.textContent = "VETITË:\n" + "Gjethet e sherbelës, në saje të esencës (të pasur në tujone), tanineve, substancave të hidhura etj., kanë veti të pakësojnë djersitjen (ky veprim shfaqet dy orë pas pirjes së çajit dhe zgjat disa ditë) dhe të shtojnë qumështin te gratë me fëmijë në gji. Për të pakësuar djersitjen përdoret, në radhë të parë, në rastet e djersitjes së tepruar gjatë natës, në klimakter, pubertet dhe në sëmundje të mushkërive. Droga është e efektshme kundër heqjes së barkut, veçanërisht kur diarreja shoqërohet me një dobësim të muskulaturës së traktit tretës (atoni gastro-intestinale). Në formën e çajit rekomandohet në trazira nervore, në të marrë të mendve, e në gjendje ligështimi. Në saje të hormoneve që përmban, droga ka tek femrat veprim oestrogjen. Sherbela rekomandohet edhe si mjet që rregullon dhe lehtëson menstruacionet (amenore, dismenore, etj.) dhe fekondimin. Droga këshillohet edhe për të normalizuar çrregullime të tretjes dhe në sëmundje të fshikëzës së tëmthit dhe të mëlçisë. Çaji i sherbelës pengon zhvillimin dhe rritjen e mikroorganizmave (antiseptik), prandaj përdoret në formë gargare dhe kolutore në acarimet e zgavrës së gojës dhe në hemorragjitë e mishrave të dhëmbëve. Në formën e ekstraktit alkoolik përdoret për t’i bërë masazh kokës në rastin e rënies së flokëve.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë gjelle me drogë të grimcuar zhyttet në një gotë me ujë të valuar; ena mbulohet me kapak, lihet në qetësi 15 minuta, pastaj përmbajtja kullohet dhe çaji pihet në masën deri 2 doza të tilla në ditë. Po ky çaj mund të përdoret nga jashtë për qëllime të ndryshme (të përshkruara në vetitë).";
    } else if (plantId === "50") {
        image.src = "../../Images/rozmarina.jpg";
        name.textContent = "Rozmarina";
        information.textContent = "Vetitë:\n" + "Gjethet e rozmarinës përmbajnë vaj esencial (të pasur me pinene, kamfur etj.) dhe alkaloidin rozmaricinë. Ato kanë veti që stimulojnë përkohësisht veprimtarinë e trurit, frymëmarrjen dhe qarkullimin e gjakut (veprim eksitues), qetësojnë spazmat e muskulaturës së butë (veprim spazmolitik), nxisin zbrazjen e fshikëzës së tëmthit dhe ndihmojnë në rregullimin dhe lehtësimin e menstruacioneve. Mjekësia popullore, e mbështetur edhe shkencërisht, e përdor rozmarinën kundër hipertensionit. Nga gjethet e saj përgatiten preparate të ndryshme që përdoren nga jashtë për trajtimin e reumatizmës artikulare, ndrydhjeve, kontuzioneve, puçrrave skrofuloze, plagëve dhe ekzemave. Në formë gargare përdoret për mjekimin e aftës, ndërsa në formë ekstrakti alkoolik përdoret për masazh të kokës kundër rënies së flokëve. Në doza të larta, rozmarina mund të shkaktojë helmim; dëmton mukozën e zorrëve dhe veshkave, shkakton gjendje dehjeje dhe dridhje. Nuk duhet të përdoret gjatë shtatzënisë.\n\n\n" + "Përgatitja dhe përdorimi:\n" + "Një lugë kafeje deri në një lugë supe me drogë të grimcuar hidhet në një enë dhe i shtohet një gotë ujë i valuar. Ena mbulohet me kapak dhe lihet të qëndrojë për 15 minuta. Çaji, i përgatitur sipas kësaj doze dhe i ëmbëlsuar sipas dëshirës, pihet 1 deri në 3 herë në ditë.";
    } else if (plantId === "51") {
        image.src = "../../Images/Murrizi.jpg";
        name.textContent = "Murrizi";
        information.textContent = "VETITË:\n" + "Drogat përmbajnë substanca flavonike, aminopurina, adeninë, adenosinë e guaninë dhe krategolaktone, derivate triterpenike (acid ursolik, oleanolik dhe krategolik). Lulja është më e pasur në lëndë vepruese; frutet përmbajnë edhe vitaminë C, B, acid citrik etj. Acidet triterpenike zgjeronjë arteret në përgjithësi dhe arteret koronare në veçanti (që furnizojnë muskulin e zemrës me gjak), dhe fuqizojnë muskulaturën e zemrës. Aminopurinat rregullojnë qarkullimin e gjakut. Drogat kanë veti qetësuese dhe ulin presionin e gjakut. Drogat veprojnë pas një kohe të gjatë. Duke u mbështetur në këto veti, drogat përdoren si mjete antisklerotike, hipotonike dhe sedative për pakësimin e zemrës së dobësuar nga shqetësime nervore, në goditjet e forta të zemrës, në vështirësi frymëmarrjeje, në rastet e presionit të ngritur të gjakut, në pagjumësi, në rastet e dhëmbjeve në zemër, dhe në rritje të ngacmueshmërisë. Drogat përdoren edhe në vështirësitë që shoqërojnë klimakterin. Me rezultate të mira mjekuese ato përdoren në format e lehta të pamjaftueshmërisë së koronareve, në çrregullimet që vijnë nga mos furnizimi i mirë me gjak i trurit, në dëmtimet e zemrës pas sëmundjeve infektive etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Dy lugë çaji drogë të grimcuara (lule ose fryte) hidhen në një enë ku shtohet një filxhan çaji me ujë që zien; ena mbulohet dhe lihet të ftohet; pastaj përmbajtja kullohet dhe lëngu ëmbëlsohet ose jo, sipas dëshirës, dhe pihet. Merren 2–3 doza të tilla në ditë. Drogat e murrizit përdoren edhe në formë tinkture, e cila përgatitet kështu: 20 g lule ose fryte të grimcuara hidhen në një shishe ku shtohen 100 g alkool 60°; përmbajtja pas 10 ditësh kullohet dhe lëngu pihet, 20–25 pika në pak ujë 3 herë në ditë; rregullon të rrahurat e zemrës dhe lehtëson gjumin.";
    } else if (plantId === "52") {
        image.src = "../../Images/Trendafili_i_eger.jpg";
        name.textContent = "Trendafili i eger";
        information.textContent = "VETITË\n" + "Frutat e trëndafilit të egër përmbajnë sasi të mëdha vitamine C, vitamine P, provitamine A, acide organike, sheqer të invertuar, taninë, esencë etj. Për shkak të kësaj përbërjeje të larmishme, droga është përdorur prej shumë kohësh si medikament dhe si pije freskuese. Përdoret si mjet rrudhës kundër heqjes së barkut te fëmijët, kundër skorbutit (dobësi, anemi, prirje për hemorragji në lëkurë e mukoza nga mungesa e vitaminës C) dhe për rritjen e rezistencës së organizmit ndaj disa sëmundjeve infektive, si p.sh. gripit etj. Frutat e trëndafilit të egër janë ndër burimet më të pasura të vitaminës C dhe rekomandohen si drogë vitaminike, veçanërisht në pranverë. Droga është e efektshme edhe në pezmatime të rrugëve urinare të sipërme dhe të poshtme. Çaji që përgatitet nga bërthamat përdoret më shpesh si mjet diuretik.\n\n\n" + "PËRGATITJA E PËRDORIMI\n" + "Çaji përgatitet duke valuar 5–10 minuta në një gotë ujë një lugë gjelle me fruta të copëtuara. Këshillohet që frutat të hidhen në ujë në çastin kur ai fillon të ziejë (në enë çingoje) dhe zierja të bëhet e ngadalshme, sepse në këtë mënyrë ruhet pa u prishur deri në një farë shkalle vitamina C. Pas ftohjes, çaji kullohet nëpër një copë napë dhe pihet menjëherë. Doza të tilla çaji mund të merren 2–3 herë gjatë ditës.";
    } else if (plantId === "53") {
        image.src = "../../Images/Trumza.jpg";
        name.textContent = "Trumza";
        information.textContent = "VETITË:\n" + "Droga përmban esencë (me karvakrol e cimol), taninë etj. Në sajë të këtyre përbërësve përdoret si mjet që nxit tretjen, largon gazrat nga zorrët, nxit nxjerrjen e gëlbazës, ndalon herjen e barkut, nxit sistemin nervor etj. Infuzi i drogës, në formë gargare, përdoret në acarimet e fytit.\n\n\n" + "PËRGATITJA E PËRDORIMIT:\n" + "Një deri tri lugë kafeje me drogë të grimcuar vlohen me një gotë me ujë që zien; ena mbulohet me kapak dhe lihet 15 minuta në qetësi. Pastaj përmbajtja kullohet dhe lëngu pihet i ëmbëlsuar. Merren tri doza të tilla në ditë.";
    } else if (plantId === "54") {
        image.src = "../../Images/Milca.jpg";
        name.textContent = "Milca";
        information.textContent = "VETITË:\n" + "Gjethet e milcës përdoren si sedative, karminative dhe spazmolitike në fryrjet e barkut nga gazët, në katarre të lehta të zorrëve e të stomakut, si dhe për të nxitur rrjedhjen e tëmthit; qetëson neurozat kardiake, rrahjet e forta të zemrës dhe çrregullimet psikoneurotike. Gjethet e milcës përmbajnë esencë me erë karakteristike si të limonit; ato ndihmojnë në prodhimin dhe sekretimin e tëmthit, ngadalësojnë rrahjet e forta të zemrës dhe ulin presionin e ngritur të gjakut, ndihmojnë kundër pagjumësisë me prejardhje nervore e në të gjitha krizat e ngërçet e barkut etj.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë supe me drogë të grimcuar hidhet në një enë ku shtohen dy gota me ujë të valuar; përmbajtja lihet për t’u ftohur 5–10 minuta, duke e tundur herë pas here; çaji kullohet, ëmbëlsohet sipas dëshirës (me mjaltë ose sheqer); pihen 2–3 gota në ditë.";
    } else if (plantId === "55") {
        image.src = "../../Images/Bliri.jpg";
        name.textContent = "Bliri";
        information.textContent = "VETITË:\n" + "Lulet e blirit përmbajnë në mucilagje, esencë të pasur, farnezol, glukozide të ndryshme, sheqerna, tanine dhe substanca të afërta me vitaminë E. Përdoren në gjendje të shkatërruara nga të ftohtit dhe që shoqërohen me temperaturë (rrufë, kollë, gjelbëzë, etj.) në sajë vetisë që kanë për të shkaktuar djersitje; përdoren gjithashtu në sëmundjet e veshkave dhe të fshikëzës urinare, si dhe për të lehtësuar dhëmbjet dhe për të përmirësuar qetësimin e stomakut. Lulet e blirit kanë edhe veti të tjera të ngjashme me ato të lules së shtogut; ato përmirësojnë gjendjen nervore si rrjedhim të gjumën të qetësojnë gjumin.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë supe me lulebliri hidhet në një enë ku shtohet 1 gotë me ujë që valon; ena mbulohet me kapak dhe lihet 5–10 minuta duke e tundur herë pas here, pastaj lëngu kullohet, ëmbëlsohet me sheqer ose me mjaltë dhe pihet i ngrohtë. Merren disa doza të tilla gjatë ditës.";
    } else if (plantId === "56") {
        image.src = "../../Images/Valeriana.jpg";
        name.textContent = "Valeriana";
        information.textContent = "VETITË:\n" + "Droga përmban kryesisht esencë të pasur me kamfen, pinen, seskuiterpene, azulene etj., alkaloidet hatinin dhe valerin (vetëm në rrënjët e freskëta), si dhe estere të acideve të ndryshme, p.sh. të acidit valerianik, valepotriate, alkoolë dhe ketone, p.sh. valenol etj. Acidi valerianik i jep drogës erën e saj specifike. Valeriana ka veti qetësuese dhe hipnotike të lehta. Përdoret si sedativ dhe spazmolitik në pagjumësinë e shkaktuar nga sforcime nervore dhe lodhje. Droga përdoret gjithashtu për të lehtësuar rrahjet e forta të zemrës, në neurozat e stomakut dhe të zorrëve, si dhe në rastet e fryrjes së zorrëve nga gazrat. Veprimi neuro-sedativ i drogës lidhet kryesisht me praninë e estereve dhe, në veçanti, të valepotriateve. Valeriana vepron në mënyrë të ngjashme me rezerpinën ose fenotiazinat, por në një shkallë më të dobët.\n\n\n" + "PËRGATITJA DHE PËRDORIMI:\n" + "Një lugë çaji me drogë të grimcuar hidhet në një enë, ku shtohet gjysmë gote ujë i valuar. Ena mbulohet me kapak dhe lihet të qëndrojë për 30 minuta. Pas kullimit, çaji pihet. Merren 2 ose 3 doza të tilla në ditë.";
    } else if (plantId === "57") {
        image.src = "../../Images/Mendra_e_kuqe.jpg";
        name.textContent = "Mendra e kuqe";
        information.textContent = "VETITË:\n" + "Mendra e butë përmban esencë të pasur me mentol, substanca tanike, të hidhura etj.; është përdorur që prej shumë kohësh si medikament popullor. Përdoret si çaj për qetësimin e sistemit nervor, për largimin e gazeve nga zorrët, për nxitjen e zbrazjes së fshikëzës së tëmthit, kundër heqjes së barkut, marrjes së mendëve etj. Kohët e fundit bëhen prova për përdorimin e drogës në uljen e presionit të gjakut; sigurisht mjekimi i hipertensionit duhet të bëhet vetëm nën mbikëqyrjen e mjekut.\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një lugë supe me mendër zhytet në dy gota (300 g) me ujë të valuar, ena mbulohet me kapak e lihet të ftohur 5–10 minuta, duke e tundur herë pas here; çaji kullohet, ëmbëlsohet sipas dëshirës me sheqer ose me mjaltë dhe pihet. Gjatë ditës merren 2 ose 3 doza të tilla.";
    } else if (plantId === "58") {
        image.src = "../../Images/Likopsi.jpg";
        name.textContent = "Likopsi:";
        information.textContent = "VETITË:\n" + "Ende nuk është zbuluar substanca vepruese e drogës, megjithatë dihet se ajo përmban esencë, glukozid likopinë, tanine, hidhëtina, rrëshirë, acid kafeik, ursolik etj. Droga ka veti qetësuese; ndikon drejtpërdrejt në përmirësimin e gjumit, si dhe në funksionimin e disa gjendrave me rrjedhje të brendshme; ka gjithashtu veti që ngadalësojnë proceset metabolike. Këshillohet si sedativ në neuroza, në rrahje të forta të zemrës, në raste të rritjes së aktivitetit të tiroides dhe në çrregullime të sistemit nervor vegjetativ. Jep efekt edhe kur përdoret për një kohë të gjatë. Nuk grumbullohet në organizëm dhe nuk është e dëmshme, prandaj mund të përdoret për një kohë të gjatë (sipas rastit, edhe disa muaj rresht).\n\n\n" + "PËRGATITJA E PËRDORIMI:\n" + "Një deri në dy lugë çaji me drogë të grimcuar hidhen në një enë ku shtohet një filxhan çaji me ujë që zien; përmbajtja lihet 15 minuta duke e përzier herë pas here; pastaj lëngu kullohet, ëmbëlsohet sipas dëshirës dhe pihet. Merren një ose dy doza të tilla në ditë.";
    }else if (plantId === "59") {
        image.src = "../../Images/Sumullbari.jpg";
        name.textContent = "Sumullbari";
        information.textContent = "VEPRIMI:\n" + "Substancat vepruese të kësaj droge ende nuk njihen plotësisht. Droga përmban rrëshira të përziera me lëndë të hidhura (humulon, lupulon etj.) dhe esencë. Falë esencës dhe lupulonit, droga ka veti qetësuese mbi sistemin nervor qendror, lehtëson gjendjet e padëshirueshme gjatë tensionit nervor dhe nxit gjumin. Gjatë grumbullimit dhe përpunimit të boçeve vërehet ndonjëherë përgjumje, e cila shkaktohet kryesisht nga lupuloni. Substancat e hidhura dhe esenca i japin drogës aftësinë për të hapur oreksin dhe për të shtuar urinimin. Në bazë të këtyre vetive, droga këshillohet si qetësuese në pagjumësi të lehta, në mbingacmueshmëri (si të natyrës seksuale ashtu edhe histerike). Gjithashtu rekomandohet si diuretik i lehtë në rastet e prostatës dhe si përmirësuese e tretjes. Droga ka edhe veti fitoncide.\n\n\n" + "PËRGATITJA DHE PËRDORIMI:\n" + "Gjysmë luge çaji me drogë të grimcuar hidhet në një enë dhe përvëlohet me gjysmë gote ujë të valuar. Ena mbulohet me kapak dhe lihet 15–30 minuta; më pas kullohet dhe lëngu pihet para gjumit. Për përmirësimin e tretjes dhe të urinimit, mund të merren dy deri në tri doza të tilla në ditë, zakonisht para buke.";
    } else if (plantId === "60") {
        image.src = "../../Images/kamomili.jpg";
        name.textContent = "Kamomili";
        information.textContent = "VEPRIMI:\n" + "Lulja e kamomilit përmban esencë me kamazulen, bisabolol, farnesen etj.; heterozide flavonike, substanca të hidhura, substanca kumarinike dhe apigeninë (me veprim spazmolitike), tanine, mucilagje, etj. Prej shumë kohë, droga është përdorur si mjet që largon gazët nga zorrët dhe që liron ngërçet (spazmat) e muskulaturës së butë të zorrëve dhe të stomakut (duke qetësuar dhe mbrojtur mukozën e organizmit, veçanërisht tek fëmijët). Ajo përdoret kundër heqjes së barkut, kundër pezmatimit të rrugëve urinare dhe si mjet që shton djersitjen dhe qetëson në tërësi e ul ngacmueshmërinë e sistemit nervor qendror. Ndihmon në mjekimin e acarimeve të ndryshme të lëkurës dhe të mukozave, të çibanëve, djegieve, etj.; përdoret edhe për shpëlarjen e syve, veshëve, hundës etj.\n\n\n" + "PERGATITJA E PËRDORIMI:\n" + "Një lugë supe me lule kamomili hidhet në një enë ku shtohet 1 gotë me ujë që valon; ena mbulohet me kapak dhe lihet 5–10 minuta duke e tundur herë pas here; lëngu kullohet dhe ëmbëlsohet sa më pak. Çaji i përgatitur pihet disa herë në ditë. Në mënyrë që të ruhen substancat vepruese, çaji i kamomilit nuk duhet të përgatitet duke u zier. Për fëmijë përdoren doza më të vogla dhe konkretisht 1 lugë kafeje me lule në një tas çaji me ujë, në formë përvalese që përgatitet si më sipër.";
    }
});